version: '3.3'
services:
  client:
    restart: unless-stopped
    container_name: fin_client
    build:
        context: .
        dockerfile: Dockerfile
    ports:
      - 8006:3000
    volumes:
      - /app-fin
    environment: 
      - REACT_APP_URL_API=http://192.168.0.20:8005/
    command: yarn start
    